import globals from 'globals';

export const react = [
  {
    files: ['**/*.{jsx,tsx}'],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    name: 'eslint-config-react',
    rules: {
      'canonical/sort-react-dependencies': 'warn',
      'react-hooks/exhaustive-deps': 'error',
      'react-hooks/rules-of-hooks': 'error',
      'react/boolean-prop-naming': ['error', { rule: '^(is|has)[A-Z]([A-Za-z0-9]?)+' }],
      'react/button-has-type': 'warn',
      'react/default-props-match-prop-types': 'off',
      'react/destructuring-assignment': 'warn',
      'react/display-name': 'warn',
      'react/forbid-component-props': 0,
      'react/forbid-dom-props': 0,
      'react/forbid-elements': 0,
      'react/forbid-foreign-prop-types': 0,
      'react/forbid-prop-types': 'warn',
      'react/function-component-definition': [
        'warn',
        {
          namedComponents: 'arrow-function',
          unnamedComponents: 'arrow-function',
        },
      ],
      'react/hook-use-state': 'warn',
      'react/iframe-missing-sandbox': 'error',
      'react/jsx-boolean-value': ['warn', 'never'],
      'react/jsx-child-element-spacing': 0,
      'react/jsx-closing-bracket-location': ['warn', 'line-aligned'],
      'react/jsx-closing-tag-location': 0,
      'react/jsx-curly-brace-presence': [
        'warn',
        {
          children: 'never',
          props: 'never',
        },
      ],
      'react/jsx-curly-newline': 'warn',
      'react/jsx-curly-spacing': [
        'warn',
        'never',
        {
          allowMultiline: true,
        },
      ],
      'react/jsx-equals-spacing': ['warn', 'never'],
      'react/jsx-filename-extension': 0,
      'react/jsx-first-prop-new-line': ['warn', 'multiline-multiprop'],
      'react/jsx-fragments': ['warn', 'syntax'],
      'react/jsx-handler-names': [
        'warn',
        {
          checkInlineFunction: false,
          checkLocalVariables: false,
          eventHandlerPrefix: 'handle',
          eventHandlerPropPrefix: 'on',
        },
      ],
      'react/jsx-indent': ['warn', 2],
      'react/jsx-indent-props': ['warn', 2],
      'react/jsx-key': [
        'error',
        {
          checkFragmentShorthand: true,
          checkKeyMustBeforeSpread: true,
        },
      ],
      'react/jsx-max-depth': 0,
      'react/jsx-max-props-per-line': [
        'warn',
        {
          maximum: 3,
          when: 'multiline',
        },
      ],
      'react/jsx-newline': [
        'warn',
        {
          prevent: true,
        },
      ],
      'react/jsx-no-bind': [
        'warn',
        {
          allowArrowFunctions: true,
          allowBind: false,
          ignoreRefs: true,
        },
      ],
      'react/jsx-no-comment-textnodes': 'error',
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-leaked-render': 'error',
      'react/jsx-no-literals': 0,
      'react/jsx-no-script-url': 'error',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-undef': 'error',
      'react/jsx-no-useless-fragment': [
        'warn',
        {
          allowExpressions: true,
        },
      ],
      'react/jsx-one-expression-per-line': 0,
      'react/jsx-pascal-case': [
        'warn',
        {
          ignore: [
            'h{}',
            'h2',
            'h3',
            'h4',
            'h5',
            'h6',
            'p',
            'a',
            'ul',
            'ol',
            'li',
            'img',
            'div',
            'span',
            'dl',
            'dt',
            'dd',
          ],
        },
      ],
      'react/jsx-props-no-multi-spaces': 'warn',
      'react/jsx-props-no-spreading': 0,
      'react/jsx-sort-props': 0,
      'react/jsx-tag-spacing': [
        'warn',
        {
          afterOpening: 'never',
          beforeSelfClosing: 'always',
          closingSlash: 'never',
        },
      ],
      'react/jsx-uses-react': 'warn',
      'react/jsx-uses-vars': 'error',
      'react/jsx-wrap-multilines': 0,
      'react/no-access-state-in-setstate': 'error',
      'react/no-adjacent-inline-elements': 0,
      'react/no-array-index-key': 'warn',
      'react/no-arrow-function-lifecycle': 'error',
      'react/no-children-prop': 'error',
      'react/no-danger': 'error',
      'react/no-danger-with-children': 'error',
      'react/no-deprecated': 'error',
      'react/no-did-mount-set-state': 'error',
      'react/no-did-update-set-state': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-find-dom-node': 'error',
      'react/no-invalid-html-attribute': 'error',
      'react/no-is-mounted': 'error',
      'react/no-multi-comp': 0,
      'react/no-namespace': 'error',
      'react/no-redundant-should-component-update': 'error',
      'react/no-render-return-value': 'error',
      'react/no-set-state': 'warn',
      'react/no-string-refs': 'error',
      'react/no-this-in-sfc': 'error',
      'react/no-typos': 'error',
      'react/no-unescaped-entities': 0,
      'react/no-unknown-property': 'error',
      'react/no-unsafe': 'error',
      'react/no-unstable-nested-components': 'error',
      'react/no-unused-class-component-methods': 'warn',
      'react/no-unused-prop-types': 'warn',
      'react/no-unused-state': 'warn',
      'react/no-will-update-set-state': 'error',
      'react/prefer-es6-class': 'warn',
      'react/prefer-exact-props': 0,
      'react/prefer-read-only-props': 'warn',
      'react/prefer-stateless-function': [
        'warn',
        {
          ignorePureComponents: true,
        },
      ],
      'react/prop-types': 0,
      'react/react-in-jsx-scope': 0,
      'react/require-default-props': 0,
      'react/require-optimization': 0,
      'react/require-render-return': 'error',
      'react/self-closing-comp': 'warn',
      'react/sort-comp': 0,
      'react/sort-default-props': 'off',
      'react/sort-prop-types': 'off',
      'react/state-in-constructor': ['warn', 'always'],
      'react/static-property-placement': 0,
      'react/style-prop-object': 'error',
      'react/void-dom-elements-no-children': 'error',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
];

export default react;
