import { type FlatConfigArray } from './types.js';

export const canonical: FlatConfigArray = [
  {
    rules: {
      'canonical/id-match': [
        2,
        '(^[A-Za-z]+(?:[A-Z\\d][a-z\\d]*)*\\d*$)|(^[A-Z]+(_[A-Z\\d]+)*(_\\d$)*$)|(^(_|\\$)$)',
        {
          ignoreDestructuring: true,
          ignoreNamedImports: true,
          onlyDeclarations: true,
          properties: true,
        },
      ],
      'unicorn/prevent-abbreviations': [
        2,
        {
          replacements: {
            props: false,
            args: false,
            pkg: false,
            ref: false,
            rel: false,
          },
          checkProperties: false,
        },
      ],
      '@stylistic/comma-dangle': [
        2,
        {
          functions: 'always-multiline',
          exports: 'always-multiline',
          imports: 'always-multiline',
          objects: 'always-multiline',
          arrays: 'always-multiline',
        },
      ],
      'id-length': [
        2,
        {
          exceptions: ['_', '$', 'a', 'b', 'x', 'y', 'z', 'e', 'u', 'q', 'c'],
          exceptionPatterns: ['^.*  =>.*$'],
          min: 2,
        },
      ],
      '@stylistic/padding-line-between-statements': [
        2,
        {
          prev: 'multiline-block-like',
          blankLine: 'always',
          next: '*',
        },
      ],
      'canonical/filename-match-regex': [
        1,
        {
          regex: '^[a-z]+(?:-[a-z0-9]+)*(?:\\.[a-z]+(?:-[a-z0-9]+)*)*$',
          ignoreExporting: false,
        },
      ],
      'unicorn/numeric-separators-style': [
        2,
        {
          number: {
            minimumDigits: 0,
            groupLength: 3,
          },
        },
      ],

      'no-useless-rename': [
        2,
        {
          ignoreDestructuring: false,
          ignoreExport: false,
          ignoreImport: false,
        },
      ],
      'no-use-before-define': [
        2,
        {
          functions: false,
          variables: true,
          classes: true,
        },
      ],
      '@stylistic/no-multiple-empty-lines': [
        2,
        {
          maxBOF: 0,
          maxEOF: 1,
          max: 1,
        },
      ],
      'canonical/destructuring-property-newline': [
        2,
        {
          allowAllPropertiesOnSameLine: false,
        },
      ],
      'no-warning-comments': [
        1,
        {
          terms: ['todo', '@toto'],
          location: 'start',
        },
      ],
      '@stylistic/array-bracket-newline': [
        2,
        {
          multiline: true,
          minItems: 1,
        },
      ],
      '@stylistic/array-element-newline': [
        2,
        {
          multiline: true,
          minItems: 1,
        },
      ],

      '@stylistic/generator-star-spacing': [
        2,
        {
          before: false,
          after: true,
        },
      ],
      '@stylistic/key-spacing': [
        2,
        {
          beforeColon: false,
          afterColon: true,
        },
      ],
      '@stylistic/switch-colon-spacing': [
        2,
        {
          before: false,
          after: true,
        },
      ],
      '@stylistic/yield-star-spacing': [
        2,
        {
          before: false,
          after: true,
        },
      ],
      '@stylistic/space-unary-ops': [
        2,
        {
          nonwords: false,
          words: true,
        },
      ],
      '@stylistic/keyword-spacing': [
        2,
        {
          before: true,
          after: true,
        },
      ],
      '@stylistic/comma-spacing': [
        2,
        {
          before: false,
          after: true,
        },
      ],
      '@stylistic/arrow-spacing': [
        2,
        {
          before: true,
          after: true,
        },
      ],
      '@stylistic/semi-spacing': [
        2,
        {
          before: false,
          after: true,
        },
      ],
      '@stylistic/quote-props': [
        2,
        'as-needed',
        {
          numbers: true,
        },
      ],
      'unicorn/no-array-reduce': [
        'error',
        {
          allowSimpleOperations: true,
        },
      ],
      'eslint-comments/disable-enable-pair': [
        2,
        {
          allowWholeFile: true,
        },
      ],
      'no-shadow': [
        2,
        {
          builtinGlobals: false,
          hoist: 'all',
        },
      ],
      'prefer-regex-literals': [
        2,
        {
          disallowRedundantWrapping: true,
        },
      ],
      '@stylistic/line-comment-position': [
        2,
        {
          position: 'above',
        },
      ],
      'unicorn/catch-error-name': [
        'error',
        {
          name: 'error',
        },
      ],
      'valid-typeof': [
        2,
        {
          requireStringLiterals: true,
        },
      ],
      'no-redeclare': [
        2,
        {
          builtinGlobals: true,
        },
      ],
      'max-statements-per-line': [
        2,
        {
          max: 1,
        },
      ],
      'no-param-reassign': [
        2,
        {
          props: false,
        },
      ],
      'no-void': [
        2,
        {
          allowAsStatement: true,
        },
      ],
      '@stylistic/function-call-argument-newline': [2, 'consistent'],
      '@stylistic/nonblock-statement-body-position': [2, 'below'],
      '@stylistic/lines-between-class-members': [2, 'always'],
      '@stylistic/space-before-function-paren': [2, 'always'],
      '@stylistic/computed-property-spacing': [2, 'never'],
      '@stylistic/implicit-arrow-linebreak': [2, 'beside'],
      'unicorn/require-number-to-fixed-digits-argument': 2,
      '@stylistic/template-curly-spacing': [2, 'never'],
      '@stylistic/array-bracket-spacing': [2, 'never'],
      '@stylistic/function-call-spacing': [2, 'never'],
      '@stylistic/space-before-blocks': [2, 'always'],
      '@stylistic/template-tag-spacing': [2, 'never'],
      'unicorn/require-post-message-target-origin': 2,
      '@stylistic/rest-spread-spacing': [2, 'never'],
      'canonical/no-import-namespace-destructure': 2,
      'unicorn/no-unreadable-array-destructuring': 0,
      'unicorn/no-useless-promise-resolve-reject': 2,
      '@stylistic/jsx-quotes': [2, 'prefer-single'],
      '@stylistic/no-whitespace-before-property': 2,
      '@stylistic/operator-linebreak': [2, 'after'],
      'grouped-accessor-pairs': [2, 'getBeforeSet'],
      'unicorn/no-invalid-remove-event-listener': 2,
      'unicorn/prefer-native-coercion-functions': 2,
      '@stylistic/one-var-declaration-per-line': 2,
      'function-paren-newline': [2, 'consistent'],
      'unicorn/no-object-as-default-parameter': 2,
      'unicorn/prefer-string-starts-ends-with': 2,
      '@stylistic/dot-location': [2, 'property'],
      '@stylistic/space-in-parens': [2, 'never'],
      '@stylistic/spaced-comment': [2, 'always'],
      'eslint-comments/no-aggregating-enable': 2,
      'eslint-comments/no-restricted-disable': 0,
      'unicorn/no-array-method-this-argument': 2,
      'unicorn/no-useless-fallback-in-spread': 2,
      'unicorn/prefer-optional-catch-binding': 2,
      'unicorn/relative-url-style': [2, 'never'],
      'unicorn/text-encoding-identifier-case': 2,
      '@stylistic/block-spacing': [2, 'always'],
      '@stylistic/linebreak-style': [2, 'unix'],
      'eslint-comments/no-duplicate-disable': 2,
      'eslint-comments/no-unlimited-disable': 2,
      'unicorn/prefer-string-trim-start-end': 2,
      'unicorn/require-array-join-separator': 2,
      '@stylistic/newline-per-chained-call': 0,
      '@stylistic/no-mixed-spaces-and-tabs': 2,
      '@stylistic/padded-blocks': [2, 'never'],
      'eslint-comments/require-description': 0,
      'unicorn/consistent-function-scoping': 2,
      'unicorn/no-array-callback-reference': 0,
      'unicorn/prefer-blob-reading-methods': 2,
      '@stylistic/multiline-comment-style': 0,
      '@stylistic/object-property-newline': 0,
      'canonical/export-specifier-newline': 2,
      'canonical/import-specifier-newline': 2,
      'unicorn/no-await-expression-member': 0,
      'unicorn/prefer-object-from-entries': 2,
      'canonical/filename-match-exported': 0,
      'eslint-comments/no-unused-disable': 0,
      'promise/prefer-await-to-callbacks': 0,
      'unicorn/no-abusive-eslint-disable': 2,
      'unicorn/prefer-add-event-listener': 0,
      'unicorn/prefer-default-parameters': 2,
      'unicorn/prefer-string-replace-all': 2,
      '@stylistic/comma-style': [2, 'last'],
      '@stylistic/wrap-iife': [2, 'inside'],
      'eslint-comments/no-unused-enable': 0,
      'unicorn/consistent-destructuring': 0,
      'unicorn/prefer-json-parse-buffer': 2,
      'unicorn/prefer-number-properties': 2,
      'unicorn/prefer-prototype-methods': 0,
      '@stylistic/lines-around-comment': 0,
      '@stylistic/object-curly-newline': 0,
      '@stylistic/object-curly-spacing': 0,
      'canonical/no-restricted-strings': 0,
      'no-unused-private-class-members': 0,
      'operator-assignment': [2, 'always'],
      'unicorn/custom-error-definition': 0,
      'unicorn/no-useless-length-check': 2,

      'unicorn/prefer-modern-math-apis': 2,
      '@stylistic/no-floating-decimal': 2,
      'canonical/no-use-extend-native': 2,
      'prefer-exponentiation-operator': 2,
      'unicorn/expiring-todo-comments': 0,
      'unicorn/no-useless-switch-case': 0,
      'unicorn/prefer-top-level-await': 0,
      '@stylistic/no-confusing-arrow': 2,
      '@stylistic/no-mixed-operators': 0,
      '@stylistic/no-trailing-spaces': 2,
      '@stylistic/quotes': [2, 'single'],
      'no-misleading-character-class': 2,
      'unicorn/explicit-length-check': 0,
      'unicorn/prefer-array-flat-map': 2,
      'unicorn/prefer-array-index-of': 2,
      'unicorn/prefer-negative-index': 0,
      'unicorn/prefer-query-selector': 2,
      '@stylistic/multiline-ternary': 0,
      'arrow-body-style': [2, 'always'],
      'no-unmodified-loop-condition': 2,
      'object-shorthand': [2, 'always'],
      'perfectionist/sort-jsx-props': 0,
      'prefer-promise-reject-errors': 2,
      'promise/prefer-await-to-then': 2,
      'unicorn/no-static-only-class': 2,
      'unicorn/no-unused-properties': 2,
      'unicorn/no-useless-undefined': 0,
      'unicorn/prefer-reflect-apply': 2,
      '@stylistic/semi': [2, 'always'],
      'canonical/filename-no-index': 0,
      'no-template-curly-in-string': 2,
      'no-unsafe-optional-chaining': 2,
      'unicorn/no-instanceof-array': 2,
      'unicorn/number-literal-case': 2,
      'unicorn/prefer-string-slice': 2,
      '@stylistic/no-extra-parens': 2,
      '@stylistic/no-multi-spaces': 2,
      '@stylistic/space-infix-ops': 2,
      'func-style': [2, 'expression'],
      'no-nonoctal-decimal-escape': 2,
      'no-promise-executor-return': 2,
      'no-shadow-restricted-names': 2,
      'perfectionist/sort-imports': 0,
      'prefer-named-capture-group': 0,
      'unicorn/empty-brace-spaces': 2,
      'unicorn/no-array-push-push': 0,
      'unicorn/no-document-cookie': 2,
      'unicorn/no-this-assignment': 2,
      'unicorn/no-unreadable-iife': 2,
      'unicorn/prefer-export-from': 2,
      'unicorn/prefer-regexp-test': 2,
      'consistent-this': [2, 'self'],
      'no-async-promise-executor': 2,
      'unicorn/no-array-for-each': 2,
      'unicorn/no-console-spaces': 0,
      'unicorn/no-keyword-prefix': 0,
      'unicorn/no-nested-ternary': 2,
      'unicorn/no-useless-spread': 2,
      'unicorn/no-zero-fractions': 2,
      'unicorn/prefer-array-find': 2,
      'unicorn/prefer-array-flat': 2,
      'unicorn/prefer-array-some': 2,
      'unicorn/prefer-code-point': 2,
      'unicorn/prefer-math-trunc': 2,
      'unicorn/prefer-type-error': 2,
      '@stylistic/no-extra-semi': 2,
      'no-empty-character-class': 2,
      'no-restricted-properties': 0,
      'no-useless-backreference': 2,
      'unicorn/new-for-builtins': 2,
      '@stylistic/arrow-parens': 0,
      'no-irregular-whitespace': 2,
      'no-unexpected-multiline': 2,
      'no-useless-computed-key': 2,
      'prefer-numeric-literals': 2,
      'unicorn/no-process-exit': 0,
      'unicorn/prefer-date-now': 2,
      'unicorn/prefer-includes': 2,
      'unicorn/template-indent': 2,
      'unicorn/throw-new-error': 2,
      '@stylistic/brace-style': 0,
      '@stylistic/indent': [2, 2],
      'class-methods-use-this': 0,
      'eslint-comments/no-use': 0,
      'max-lines-per-function': 0,
      'no-useless-constructor': 2,
      'require-atomic-updates': 2,
      'require-unicode-regexp': 2,
      'unicode-bom': [2, 'never'],
      'unicorn/prefer-set-has': 0,
      'unicorn/prefer-ternary': 0,
      'unicorn/string-content': 0,
      '@stylistic/new-parens': 2,
      '@stylistic/wrap-regex': 0,
      'array-callback-return': 2,
      'func-names': [2, 'never'],
      'no-constant-condition': 0,
      'no-constructor-return': 2,
      'no-dupe-class-members': 2,
      'no-extra-boolean-cast': 2,
      'no-inner-declarations': 2,
      'no-prototype-builtins': 2,
      'no-restricted-exports': 0,
      'no-restricted-globals': 0,
      'no-restricted-imports': 0,
      'no-unused-expressions': 2,
      'prefer-arrow-callback': 2,
      'unicorn/error-message': 2,
      'unicorn/filename-case': 0,
      'unicorn/no-empty-file': 2,
      'unicorn/no-hex-escape': 2,
      'unicorn/no-new-buffer': 2,
      'unicorn/prefer-spread': 0,
      'unicorn/prefer-switch': 0,
      'capitalized-comments': 1,
      'max-classes-per-file': 0,
      'max-nested-callbacks': 0,
      'no-array-constructor': 2,
      'no-case-declarations': 2,
      'no-duplicate-imports': 0,
      'no-implicit-coercion': 2,
      'no-loss-of-precision': 2,
      'no-negated-condition': 2,
      'no-restricted-syntax': 0,
      'no-this-before-super': 2,
      'no-underscore-dangle': 0,
      'prefer-destructuring': 0,
      'prefer-object-spread': 2,
      'promise/valid-params': 2,
      'semi-style': [2, 'last'],
      'unicorn/better-regex': 2,
      'unicorn/import-style': 0,
      'unicorn/no-lonely-if': 2,
      'unicorn/no-new-array': 2,
      '@stylistic/eol-last': 2,
      'no-compare-neg-zero': 2,
      'no-implicit-globals': 2,
      'no-unneeded-ternary': 2,
      'no-unreachable-loop': 2,
      'promise/param-names': 2,
      'unicorn/escape-case': 2,
      'unicorn/no-for-loop': 2,
      'unicorn/no-thenable': 2,
      '@stylistic/max-len': 0,
      '@stylistic/no-tabs': 2,
      'default-param-last': 2,
      'func-name-matching': 2,
      'no-inline-comments': 2,
      'no-unsafe-negation': 2,
      'one-var': [2, 'never'],
      'prefer-rest-params': 2,
      'symbol-description': 2,
      'consistent-return': 2,
      'constructor-super': 2,
      'default-case-last': 0,
      'init-declarations': 0,
      'no-duplicate-case': 2,
      'no-invalid-regexp': 2,
      'no-nested-ternary': 0,
      'no-unsafe-finally': 2,
      'no-useless-concat': 2,
      'no-useless-escape': 2,
      'no-useless-return': 2,
      'unicorn/prefer-at': 0,
      'block-scoped-var': 2,
      'no-await-in-loop': 0,
      'no-control-regex': 2,
      'no-empty-pattern': 2,
      'no-extend-native': 2,
      'no-global-assign': 2,
      'no-import-assign': 2,
      'no-magic-numbers': 0,
      'no-return-assign': 2,
      'no-setter-return': 2,
      'no-sparse-arrays': 2,
      'no-throw-literal': 2,
      'no-unused-labels': 2,
      'no-useless-catch': 2,
      'no-class-assign': 2,
      'no-const-assign': 2,
      'no-dupe-else-if': 2,
      'no-implied-eval': 2,
      'no-invalid-this': 0,
      'no-multi-assign': 2,
      'no-new-wrappers': 2,
      'no-octal-escape': 2,
      'no-regex-spaces': 2,
      'no-self-compare': 2,
      'no-useless-call': 2,
      'prefer-template': 0,
      strict: [2, 'never'],
      'unicorn/no-null': 0,
      'accessor-pairs': 2,
      complexity: [2, 30],
      'max-statements': 0,
      'no-cond-assign': 2,
      'no-else-return': 0,
      'no-extra-label': 2,
      'no-fallthrough': 0,
      'no-func-assign': 2,
      'no-lone-blocks': 2,
      'no-self-assign': 2,
      'no-unreachable': 0,
      'no-unused-vars': 2,
      'for-direction': 2,
      'getter-return': 2,
      'no-delete-var': 2,
      'no-extra-bind': 2,
      'no-new-object': 2,
      'no-new-symbol': 2,
      'no-script-url': 2,
      'no-undef-init': 2,
      'prefer-spread': 2,
      'require-await': 0,
      'require-yield': 2,
      yoda: [2, 'never'],
      'default-case': 0,
      'dot-notation': 2,
      'guard-for-in': 2,
      'no-div-regex': 2,
      'no-dupe-args': 2,
      'no-dupe-keys': 2,
      'no-ex-assign': 2,
      'no-label-var': 2,
      'no-lonely-if': 2,
      'no-loop-func': 2,
      'no-multi-str': 2,
      'no-obj-calls': 2,
      'no-sequences': 2,
      'no-undefined': 0,
      'prefer-const': 2,
      'sort-imports': 0,
      'id-denylist': 0,
      'no-continue': 0,
      'no-debugger': 2,
      'no-iterator': 2,
      'no-new-func': 2,
      'no-plusplus': 0,
      'vars-on-top': 2,
      'max-params': 0,
      'no-bitwise': 2,
      'no-console': 2,
      'no-eq-null': 2,
      'no-ternary': 0,
      'max-depth': 0,
      'max-lines': 0,
      'no-caller': 2,
      'no-labels': 2,
      'sort-keys': 0,
      'sort-vars': 2,
      'use-isnan': 2,
      'id-match': 0,
      'no-alert': 2,
      'no-empty': 2,
      'no-octal': 2,
      'no-proto': 2,
      'no-undef': 2,
      camelcase: 1,
      'new-cap': 0,
      'no-eval': 2,
      'no-with': 2,
      'no-new': 2,
      'no-var': 2,
      eqeqeq: 2,
      curly: 2,
      radix: 2,
    },
    settings: {
      'import/extensions': ['.js', '.jsx', '.mjs', '.ts', '.tsx'],
    },
    files: ['**/*.{js,jsx,cjs,mjs,ts,tsx}'],
  },
];

export default canonical;
