import jsoncParser from 'jsonc-eslint-parser';
import { type FlatConfigArray } from './types.js';

export const json: FlatConfigArray = [
  {
    rules: {
      'jsonc/sort-keys': [
        1,
        'asc',
        {
          caseSensitive: false,
          natural: true,
        },
      ],
      'jsonc/array-bracket-newline': 0,
      'jsonc/array-element-newline': 0,
      'jsonc/vue-custom-block/no-parsing-error': 0,
      'jsonc/no-escape-sequence-in-identifier': 2,
      'jsonc/no-hexadecimal-numeric-literals': 2,
      'jsonc/no-unicode-codepoint-escapes': 2,
      'jsonc/no-binary-numeric-literals': 2,
      'jsonc/no-octal-numeric-literals': 2,
      'jsonc/object-property-newline': 0,
      'jsonc/array-bracket-spacing': 0,
      'jsonc/comma-style': 0,
      'jsonc/no-numeric-separators': 2,
      'jsonc/no-binary-expression': 2,
      'jsonc/no-template-literals': 2,
      'jsonc/object-curly-newline': 0,
      'jsonc/object-curly-spacing': 1,
      'jsonc/no-floating-decimal': 2,
      'jsonc/no-bigint-literals': 2,
      'jsonc/no-regexp-literals': 2,
      'jsonc/no-undefined-value': 2,
      'jsonc/no-useless-escape': 2,
      'jsonc/sort-array-values': 0,
      'jsonc/valid-json-number': 2,
      'jsonc/no-parenthesized': 2,
      'jsonc/no-sparse-arrays': 2,
      'jsonc/key-name-casing': 0,
      'jsonc/no-number-props': 2,
      'jsonc/no-octal-escape': 2,
      'jsonc/space-unary-ops': 2,
      'jsonc/comma-dangle': 0,
      'jsonc/no-dupe-keys': 2,
      'jsonc/no-multi-str': 2,
      'jsonc/no-plus-sign': 2,
      'jsonc/indent': 0,
      'jsonc/key-spacing': 0,
      'jsonc/no-comments': 1,
      'jsonc/no-infinity': 2,
      'jsonc/quote-props': 0,
      'jsonc/no-octal': 2,
      'jsonc/no-nan': 2,
      'jsonc/quotes': 0,
      'jsonc/auto': 0,
    },
    languageOptions: {
      parser: jsoncParser,
    },
    files: ['**/*.json'],
  },
];

export default json;
