/**
 * https://github.com/ota-meshi/eslint-plugin-regexp/blob/master/lib/configs/recommended.ts
 */
import { type FlatConfigArray } from './types.js';

export const regexp: FlatConfigArray = [
  {
    rules: {
      'regexp/no-potentially-useless-backreference': 'warn',
      'regexp/no-dupe-characters-character-class': 2,
      'regexp/optimal-lookaround-quantifier': 'warn',
      'regexp/optimal-quantifier-concatenation': 1,
      'regexp/prefer-unicode-codepoint-escapes': 1,
      'regexp/no-empty-lookarounds-assertion': 2,
      'regexp/no-trivially-nested-quantifier': 2,
      'regexp/no-useless-dollar-replacements': 2,
      'regexp/no-useless-non-capturing-group': 1,
      'regexp/no-useless-two-nums-quantifier': 2,
      'regexp/no-trivially-nested-assertion': 2,
      'regexp/no-super-linear-backtracking': 2,
      'regexp/prefer-predefined-assertion': 1,
      'regexp/no-useless-character-class': 1,
      'regexp/prefer-question-quantifier': 1,
      'regexp/confusing-quantifier': 'warn',
      'regexp/no-empty-alternative': 'warn',
      'regexp/no-unused-capturing-group': 1,
      'regexp/control-character-escape': 1,
      'regexp/no-empty-capturing-group': 2,
      'regexp/no-useless-backreference': 2,
      'no-misleading-character-class': 2,
      'regexp/no-invisible-character': 2,
      'regexp/prefer-character-class': 1,
      'regexp/prefer-plus-quantifier': 1,
      'regexp/prefer-star-quantifier': 1,
      'no-useless-backreference': 'off',
      'regexp/no-optional-assertion': 2,
      'regexp/no-useless-assertions': 2,
      'regexp/no-useless-quantifier': 2,
      'regexp/no-dupe-disjunctions': 2,
      'regexp/no-non-standard-flag': 2,
      'regexp/no-useless-flag': 'warn',
      'regexp/no-escape-backspace': 2,
      'regexp/no-legacy-features': 2,
      'regexp/no-zero-quantifier': 2,
      'no-empty-character-class': 0,
      'regexp/no-invalid-regexp': 2,
      'regexp/no-lazy-ends': 'warn',
      'regexp/no-useless-escape': 2,
      'regexp/no-obscure-range': 2,
      'regexp/no-useless-range': 2,
      'regexp/no-useless-lazy': 2,
      'no-invalid-regexp': 'off',
      'prefer-regex-literals': 2,
      'regexp/no-empty-group': 2,
      'regexp/prefer-range': 1,
      'regexp/sort-flags': 1,
      'no-control-regex': 2,
      'regexp/match-any': 2,
      'no-regex-spaces': 2,
      'regexp/negation': 1,
      'regexp/prefer-d': 1,
      'regexp/prefer-w': 1,
      'regexp/strict': 2,
    },
    files: ['**/*.{js,jsx,cjs,mjs,ts,tsx}'],
    name: 'regexp/recommended',
  },
];

export default regexp;
